# Generated by Django 3.1.1 on 2020-09-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
