# Generated by Django 3.1.1 on 2020-09-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(upload_to='images/', verbose_name='添付画像'),
        ),
    ]
